---
title: "Datathon"
author: "Yimo Zhang"
date: "2018.3.3"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setting
```{r}
library(dplyr)
library(ggplot2)
gg_theme = theme_bw()+
           theme(panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
```

#functions
```{r}
getSeason <- function(DATES) {
    WS <- as.Date("2012-12-15", format = "%Y-%m-%d") # Winter Solstice
    SE <- as.Date("2012-3-15",  format = "%Y-%m-%d") # Spring Equinox
    SS <- as.Date("2012-6-15",  format = "%Y-%m-%d") # Summer Solstice
    FE <- as.Date("2012-9-15",  format = "%Y-%m-%d") # Fall Equinox

    # Convert dates from any year to 2012 dates
    d <- as.Date(strftime(DATES, format="2012-%m-%d"))

    ifelse (d >= WS | d < SE, "Winter",
      ifelse (d >= SE & d < SS, "Spring",
        ifelse (d >= SS & d < FE, "Summer", "Fall")))
}
```



#EDA
```{r}
summary(category)
category = category %>%
  mutate(store_id = as.character(store_id), season = getSeason(as.Date(as.character(date), format = "%Y-%m-%d")), month = month(as.character(date)), weekday = format(as.Date(as.character(date)), format="%A"))


overall = overall %>%
  mutate(store_id = as.character(store_id), season = getSeason(as.Date(as.character(date), format = "%Y-%m-%d")), month = month(as.character(date)), weekday = format(as.Date(as.character(date)), format="%A"))

category_week = category%>%
  group_by(weekday, region)%>%
  summarise(total_sale = sum(total_sales))

ggplot(data = category_week)+
  geom_line(aes(x = weekday, y = total_sale, group = region, color = region))+gg_theme

category_season = category%>%
  group_by(season)%>%
  summarise(total_sale = sum(total_sales))

category_month = category%>%
  group_by(month)%>%
  summarise(total_sale = sum(total_sales))
```

